name: drivesense
description: "Driver Assistant App."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  google_maps_flutter: ^2.10.0
  curved_navigation_bar: ^1.0.3
  video_player: ^2.8.1
  camera: ^0.11.0+2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  image: ^4.3.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fl_chart: ^0.63.0

  # Recommended lints for good coding practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
